version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - "**/*"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      xunit:
        patterns:
          - xunit*
      coverlet:
        patterns:
          - coverlet*
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    groups:
      codeql:
        patterns:
          - "github/codeql-action*"
  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    cooldown:
      default-days: 7
