name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev", "feature/*" ]
  pull_request:
    branches: [ "main", "dev" ]
  merge_group:
    branches: [ "main", "dev" ]

permissions:
  contents: read #those permissions are required to run the codeql analysis
  actions: read
  code-quality: write
  pull-requests: read
  security-events: write

jobs:
  build-and-test:
    runs-on: windows-latest
    env:
      solutionName: Microsoft.Kiota.slnx
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup .NET 8 and 10
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            8.x
            10.x
      - name: Initialize CodeQL
        uses: github/codeql-action/init@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          languages: csharp
      - name: Restore dependencies
        run: dotnet restore ${{ env.solutionName }}
      - name: Check formatting
        run: dotnet format ${{ env.solutionName }} --verify-no-changes
      - name: Build
        run: dotnet build ${{ env.solutionName }} --no-restore
          /p:UseSharedCompilation=false
      - name: Test for net472
        run: dotnet test --solution ${{ env.solutionName }} --no-build --verbosity
          normal --framework net472 --report-gh
      - name: Test for net10.0 and collect coverage
        run: dotnet test --solution ${{ env.solutionName }} --no-build --verbosity
          normal --framework net10.0 --results-directory=./TestResults --coverlet --coverlet-output-format
          cobertura --report-gh
      - name: Install report generator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Generate coverage report
        run: reportgenerator "-reports:TestResults/coverage.cobertura.*.xml" "-targetdir:.\reports\coverage" "-reporttypes:Html;MarkdownSummaryGithub;Cobertura"
      - name: Add coverage to job summary
        run: Get-Content .\reports\coverage\SummaryGithub.md >> $env:GITHUB_STEP_SUMMARY
      - name: Upload coverage report
        uses: actions/upload-code-coverage@d8e329117199404bba6fc81efe8093dc7c015e34 # v1.4.2
        if: github.event_name != 'merge_group' && ((github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]') || (github.event_name != 'pull_request' && github.ref_name == github.event.repository.default_branch))
        with:
          file: .\reports\coverage\Cobertura.xml
          language: CSharp
          label: code-coverage/dotnet
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
